//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppManage.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apps
    {
        public int Id { get; set; }
        public string app_name { get; set; }
        public string app_image { get; set; }
        public Nullable<int> app_catalogId { get; set; }
        public string app_exec_path { get; set; }
    }
}
